env:
  browser: true
  es2020: true
extends:
  - eslint:recommended
  - standard
  - prettier

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules: {
  "prettier/prettier":"error",
}
